/* ============ signal lexicon: [key, regex, github topic, label] ============ */
export const LEX = [
['react',/\breact(?!\s?native)\b|\bjsx\b/i,'react','React'],
['react-native',/\breact\s?native\b/i,'react-native','React Native'],
['nextjs',/\bnext\.?js\b/i,'nextjs','Next.js'],
['vue',/\bvue(?!\w)|\bnuxt\b/i,'vue','Vue'],
['svelte',/\bsvelte|\bsveltekit\b/i,'svelte','Svelte'],
['astro',/\bastro\b/i,'astro','Astro'],
['angular',/\bangular\b/i,'angular','Angular'],
['typescript',/\btypescript\b|\btsx\b|\bts\b(?=[\s,.;])/i,'typescript','TypeScript'],
['javascript',/\bjavascript\b|\bjs\b(?=[\s,.;])|\besm\b|\bcjs\b/i,'javascript','JavaScript'],
['node',/\bnode(\.?js)?\b|\bnpm\b|\bpnpm\b|\byarn\b/i,'nodejs','Node.js'],
['deno',/\bdeno\b/i,'deno','Deno'],
['bun',/\bbun\b/i,'bun','Bun'],
['python',/\bpython\b|\bpip\b|\bvenv\b|\buv\b(?=[\s,.;])/i,'python','Python'],
['fastapi',/\bfastapi\b/i,'fastapi','FastAPI'],
['django',/\bdjango\b/i,'django','Django'],
['flask',/\bflask\b/i,'flask','Flask'],
['rails',/\brails\b/i,'ruby-on-rails','Rails'],
['ruby',/\bruby\b/i,'ruby','Ruby'],
['rust',/\brust\b|\bcargo\b/i,'rust','Rust'],
['golang',/\bgolang\b|\bgo\b(?=\s?1\.\d)|\bgo modules?\b/i,'go','Go'],
['java',/\bjava\b(?!script)|\bspring\b/i,'java','Java'],
['kotlin',/\bkotlin\b|\bktor\b/i,'kotlin','Kotlin'],
['swift',/\bswiftui\b|\bswift\b/i,'swift','Swift'],
['flutter',/\bflutter\b|\bdart\b/i,'flutter','Flutter'],
['tailwind',/\btailwind\b/i,'tailwindcss','Tailwind'],
['css',/\bcss\b|\bscss\b|\bsass\b|\bstyled components\b/i,'css','CSS'],
['graphql',/\bgraphql\b|\bapollo\b/i,'graphql','GraphQL'],
['grpc',/\bgrpc\b|\bprotobuf\b/i,'grpc','gRPC'],
['rest',/\brest(ful)?\s?api|\bopenapi\b|\bswagger\b/i,'openapi','REST/OpenAPI'],
['postgres',/\bpostgres(ql)?\b/i,'postgresql','PostgreSQL'],
['mysql',/\bmysql\b|\bmariadb\b/i,'mysql','MySQL'],
['sqlite',/\bsqlite\b/i,'sqlite','SQLite'],
['mongodb',/\bmongo(db)?\b/i,'mongodb','MongoDB'],
['redis',/\bredis\b/i,'redis','Redis'],
['prisma',/\bprisma\b/i,'prisma','Prisma'],
['drizzle',/\bdrizzle\b/i,'drizzle-orm','Drizzle'],
['supabase',/\bsupabase\b/i,'supabase','Supabase'],
['firebase',/\bfirebase\b/i,'firebase','Firebase'],
['docker',/\bdocker\b|\bdockerfile\b/i,'docker','Docker'],
['kubernetes',/\bkubernetes\b|\bk8s\b/i,'kubernetes','Kubernetes'],
['terraform',/\bterraform\b/i,'terraform','Terraform'],
['aws',/\baws\b|\bs3\b|\blambda\b/i,'aws','AWS'],
['gh-actions',/\bgithub actions\b|\bci\/cd\b/i,'github-actions','GitHub Actions'],
['vite',/\bvite\b/i,'vite','Vite'],
['webpack',/\bwebpack\b|\bbundler\b/i,'webpack','Webpack'],
['eslint',/\beslint\b|\blinting\b/i,'eslint','ESLint'],
['prettier',/\bprettier\b/i,'prettier','Prettier'],
['jest',/\b(jest|vitest)\b|\bunit tests?\b/i,'jest','Jest/Vitest'],
['playwright',/\bplaywright\b|\bpuppeteer\b|\be2e\b/i,'playwright','Playwright'],
['pytest',/\bpytest\b/i,'pytest','pytest'],
['storybook',/\bstorybook\b/i,'storybook','Storybook'],
['electron',/\belectron\b/i,'electron','Electron'],
['tauri',/\btauri\b/i,'tauri','Tauri'],
['pytorch',/\bpytorch\b|\btorch\b/i,'pytorch','PyTorch'],
['tensorflow',/\btensorflow\b|\bkeras\b/i,'tensorflow','TensorFlow'],
['llm',/\bllms?\b|\blangchain\b|\bopenai\b|\bollama\b|\bagents?\b|\brag\b/i,'llm','LLM/Agents'],
['cli',/\bcli\b|command.line/i,'cli','CLI'],
['zsh',/\bzsh\b|\bbash\b|\bfish\b/i,'shell','Shells'],
['lua',/\blua\b|\bneovim\b/i,'lua','Lua/Neovim'],
['php',/\bphp\b|\blaravel\b/i,'php','PHP'],
['elixir',/\belixir\b|\bphoenix\b/i,'elixir','Elixir'],
['dotnet',/\b\.net\b|\bc#|netcore\b/i,'dotnet','.NET'],
['monorepo',/\bmonorepo\b|\bturborepo\b|\bnx\b/i,'monorepo','Monorepo'],
];

/* stack → pains you probably have (for idea generation) */
export const STACK_PAINS = {
react:['forms','css','state','fetching'], nextjs:['auth','css','fetching','deploy'],
vue:['state','css','fetching'], svelte:['state','css'], angular:['state','fetching'],
typescript:['types','tests','fetching'], javascript:['types','tests'],
node:['tests','errors','deploy'], python:['tests','logging','migrations','schedule'],
fastapi:['auth','migrations','docs'], django:['forms','tests','migrations'], flask:['forms','migrations'],
rails:['forms','tests','migrations'], rust:['terminal','tests'], golang:['terminal','deploy'],
tailwind:['css'], css:['css'], graphql:['fetching','types'],
postgres:['migrations'], mysql:['migrations'], sqlite:['migrations'], mongodb:['migrations'],
prisma:['migrations'], drizzle:['migrations'], supabase:['auth','migrations'], firebase:['auth','state'],
docker:['deploy'], kubernetes:['deploy','logging'], terraform:['deploy','secrets'], aws:['deploy','secrets'],
'gh-actions':['ci'], vite:['ci'], webpack:['ci'], jest:['tests'], playwright:['tests'], pytest:['tests'],
electron:['deploy','errors'], tauri:['deploy','errors'], pytorch:['llm'], tensorflow:['llm'], llm:['llm'],
cli:['terminal'], zsh:['terminal','dotfiles'], lua:['dotfiles'], php:['deploy'], elixir:['logging'],
dotnet:['tests','deploy'], monorepo:['ci','git'],
};

/* ============ pain map: what hurts → what to search ============ */
export const PAINS = [
{id:'tests',dx:'SLOW TESTS',say:'my test suite is slow and flaky',kws:['test','tests','testing','flaky','slow','coverage','tdd','jest','vitest','playwright','e2e','specs'],qs:['test framework topic:testing stars:>=1000','vitest vite test runner','playwright browser testing'],adj:['ci','types']},
{id:'auth',dx:'AUTH BOILERPLATE',say:'I keep rewriting auth boilerplate',kws:['auth','authentication','login','signin','oauth','jwt','session','sso','password'],qs:['authentication topic:auth stars:>=1000','next-auth nextjs authentication','lucia auth session'],adj:['forms','secrets']},
{id:'forms',dx:'FORM PAIN',say:'forms and validation are a drag',kws:['form','forms','validation','validate','input','zod','yup','schema','submit'],qs:['react hook form','form validation topic:forms','zod typescript schema'],adj:['types','state']},
{id:'secrets',dx:'ENV & SECRETS MESS',say:'env vars and secrets are a mess',kws:['env','environment','dotenv','secrets','secret','credentials','config','keys','token'],qs:['environment variables manager','direnv','secrets management topic:secrets'],adj:['deploy','ci']},
{id:'logging',dx:'FLYING BLIND',say:'I am flying blind — need logging and observability',kws:['log','logs','logging','observability','monitoring','telemetry','tracing','metrics','debugging'],qs:['structured logging','opentelemetry topic:observability','loki log aggregation'],adj:['errors','deploy']},
{id:'errors',dx:'UNCAUGHT ERRORS',say:'I need real error tracking',kws:['error','errors','exception','crash','crashes','sentry','stacktrace','bug'],qs:['error tracking self hosted','sentry alternative','exception handling topic:errors'],adj:['logging']},
{id:'migrations',dx:'DATA SHAPE DRIFT',say:'database migrations and schemas are a headache',kws:['migration','migrations','database','sql','postgres','orm','schema','prisma','drizzle','queries'],qs:['database migration tool','prisma orm database','drizzle orm typescript'],adj:['secrets','tests']},
{id:'css',dx:'CSS FATIGUE',say:'css and responsive layout are a slog',kws:['css','style','styling','styles','tailwind','scss','sass','responsive','layout','design'],qs:['tailwind css','utility first css','css framework topic:css stars:>=2000'],adj:['state','docs']},
{id:'state',dx:'STATE SPAGHETTI',say:'global state has become spaghetti',kws:['state','states','redux','store','signal','signals','rerender','re-render','prop drilling'],qs:['state management topic:state','zustand react store','signals reactive state'],adj:['fetching','css']},
{id:'fetching',dx:'DATA-FETCH DRAG',say:'data fetching and caching are a mess',kws:['fetch','fetching','api','apis','cache','caching','swr','react-query','refetch'],qs:['data fetching react query','tanstack query','api client typescript'],adj:['types','state']},
{id:'deploy',dx:'DEPLOY FRICTION',say:'deploying is full of friction',kws:['deploy','deployment','devops','docker','kubernetes','hosting','server','servers','infrastructure','vps'],qs:['docker compose topic:docker','self hosted topic:self-hosted stars:>=3000','deployment tools stars:>=2000'],adj:['ci','secrets']},
{id:'ci',dx:'SLOW BUILDS',say:'my CI builds and bundling are slow',kws:['build','builds','ci','pipeline','pipelines','actions','compile','compilation','bundle','bundler','webpack'],qs:['esbuild fast bundler','turborepo monorepo build','github actions topic:ci'],adj:['tests','deploy']},
{id:'git',dx:'GIT CONFUSION',say:'git workflows confuse the whole team',kws:['git','merge','merges','rebase','commit','commits','branch','branches','pull request','monorepo'],qs:['git cli topic:git stars:>=2000','lazygit terminal git','conventional commits'],adj:['docs','terminal']},
{id:'docs',dx:'DOC ROT',say:'documentation keeps rotting',kws:['docs','documentation','readme','mdx','wiki','onboarding','guide'],qs:['documentation generator topic:documentation','docusaurus docs site','mdx docs stars:>=3000'],adj:['git','pdf']},
{id:'pdf',dx:'PDF & REPORT HELL',say:'generating pdfs and reports is hell',kws:['pdf','pdfs','report','reports','invoice','export','print','docx','excel','spreadsheet','csv'],qs:['pdf generation topic:pdf','typst typesetting','excel spreadsheet parser'],adj:['docs']},
{id:'schedule',dx:'FRAGILE JOBS',say:'background jobs and cron are fragile',kws:['cron','scheduler','scheduling','job','jobs','queue','background','worker','async','task'],qs:['job queue topic:queue stars:>=1000','cron scheduler','workflow orchestration stars:>=3000'],adj:['errors','deploy']},
{id:'terminal',dx:'WEAK TERMINAL',say:'my terminal setup is weak',kws:['terminal','shell','zsh','bash','prompt','tmux','cli','command line'],qs:['terminal topic:terminal stars:>=5000','starship shell prompt','modern cli tools stars:>=3000'],adj:['dotfiles','git']},
{id:'dotfiles',dx:'MACHINE SETUP PAIN',say:'setting up a new machine takes days',kws:['dotfiles','machine','setup','provision','bootstrap','nix','brew','laptop'],qs:['dotfiles topic:dotfiles stars:>=1000','chezmoi dotfiles manager','nix home manager'],adj:['terminal','secrets']},
{id:'llm',dx:'LLM TOOLING HUNGER',say:'I want to wire up local llms and agents',kws:['llm','llms','ai','agent','agents','openai','ollama','prompt','prompts','rag','embedding','chatbot'],qs:['llm agents topic:ai stars:>=1000','ollama local llm','local llm tools stars:>=2000'],adj:['terminal','docs']},
{id:'types',dx:'RUNTIME TYPE BITES',say:'runtime types keep biting me',kws:['type','types','typescript','runtime','validation','any','schema','generic','generics'],qs:['typescript runtime validation','zod schema validation','type safe topic:typescript stars:>=3000'],adj:['tests','fetching']},
];

/* ============ offline field ledger (curated, approximate counts) ============ */
export const LEDGER = {
tests:[['vitest-dev/vitest','A blazing fast unit test framework powered by Vite.','TypeScript',63000],['microsoft/playwright','Powerful end-to-end testing for modern web apps.','TypeScript',66000],['jestjs/jest','Delightful JavaScript testing with a focus on simplicity.','TypeScript',64000],['pytest-dev/pytest','The pytest framework makes small tests readable and scalable.','Python',12500],['mswjs/msw','Seamless REST/GraphQL API mocking using service workers.','TypeScript',16000]],
auth:[['nextauthjs/next-auth','Authentication for Next.js — OAuth, magic links, sessions.','TypeScript',25000],['keycloak/keycloak','Open-source identity and access management for modern applications.','Java',24000],['goauthentik/authentik','Flexible identity provider with SSO, SAML, OAuth2 and LDAP.','Python',14000],['lucia-auth/lucia','Authentication library that abstracts session handling away.','TypeScript',10000]],
forms:[['react-hook-form/react-hook-form','Performant, flexible forms with easy validation for React.','TypeScript',42000],['colinhacks/zod','TypeScript-first schema validation with static type inference.','TypeScript',34000],['shadcn-ui/ui','Beautifully designed components you copy into your apps — forms included.','TypeScript',72000],['jquense/yup','Dead-simple object schema validation for JavaScript.','JavaScript',12000]],
secrets:[['direnv/direnv','Per-directory environment variables for your shell.','Go',12000],['dotenvx/dotenvx','A better dotenv — run anywhere, multi-environment, encrypted.','JavaScript',3000],['mozilla/sops','Simple and flexible tool for managing secrets in configuration files.','Go',17000],['hashicorp/vault','A tool for secrets management, encryption and privileged access.','Go',31000]],
logging:[['pinojs/pino','Super-fast, all-purpose JSON logger for Node.js.','JavaScript',15000],['grafana/loki','Like Prometheus, but for logs — horizontally scalable aggregation.','Go',24000],['SigNoz/signoz','Open-source observability: traces, logs and metrics in one app.','TypeScript',20000],['loguru/loguru','Python logging made (stupidly) simple and pleasant.','Python',20000]],
errors:[['getsentry/sentry','Developer-first error tracking and performance monitoring.','Python',39000],['getsentry/self-hosted','Run Sentry on your own infrastructure.','Shell',8000],['posthog/posthog','Product analytics, flags and session replay you can self-host.','TypeScript',24000],['glitchtip/glitchtip','Open-source error tracking, Sentry-compatible.','Python',2000]],
migrations:[['prisma/prisma','Next-generation ORM for Node.js and TypeScript — schema and migrations.','TypeScript',41000],['drizzle-team/drizzle-orm','Lightweight, SQL-like TypeScript ORM with zero ceremony.','TypeScript',27000],['golang-migrate/migrate','Database migrations written in Go, as CLI or library.','Go',16000],['sqlalchemy/alembic','Lightweight database migration tool for SQLAlchemy.','Python',3000]],
css:[['tailwindlabs/tailwindcss','A utility-first CSS framework for rapid UI building.','TypeScript',82000],['unocss/unocss','Instant, on-demand, atomic CSS engine.','TypeScript',17000],['styled-components/styled-components','Visual primitives for the component age.','TypeScript',17000],['shadcn-ui/ui','Copy-paste, beautifully designed, accessible components.','TypeScript',72000]],
state:[['pmndrs/zustand','A small, fast and scalable state-management solution for React.','TypeScript',47000],['reduxjs/redux','Predictable state container for JavaScript apps.','TypeScript',61000],['immerjs/immer','Create the next immutable state by mutating the current one.','TypeScript',28000],['solidjs/solid','Fine-grained reactivity with signals — no virtual DOM.','TypeScript',32000]],
fetching:[['TanStack/query','Powerful async state management and server-state caching for TS/JS.','TypeScript',41000],['trpc/trpc','Move API logic into functions — end-to-end typesafe APIs.','TypeScript',36000],['vercel/swr','React Hooks for data fetching, caching and revalidation.','TypeScript',24000],['axios/axios','Promise-based HTTP client for the browser and Node.','JavaScript',105000]],
deploy:[['docker/compose','Define and run multi-container applications with one command.','Go',33000],['coollabsio/coolify','Open-source, self-hostable Heroku/Netlify alternative.','PHP',35000],['dokku/dokku','The smallest PaaS you have ever seen — git push to deploy.','Shell',27000],['basecamp/kamal','Deploy web apps anywhere with a single command.','Ruby',12000]],
ci:[['evanw/esbuild','An extremely fast JavaScript bundler and minifier.','Go',38000],['vercel/turborepo','High-performance build system for JavaScript monorepos.','Rust',26000],['nektos/act','Run your GitHub Actions locally — no pushes required.','Go',55000],['web-infra-dev/rspack','A fast Rust-based web bundler, webpack-compatible.','Rust',10000]],
git:[['jesseduffield/lazygit','Simple terminal UI for git commands — no memorizing flags.','Go',48000],['so-fancy/diff-so-fancy','Good-looking diffs, one commit at a time.','Perl',17000],['gitbutlerapp/gitbutler','A Git client for simultaneous branches on top of your trunk.','TypeScript',13000],['conventional-changelog/conventional-changelog','Generate changelogs from conventional commit history.','JavaScript',7000]],
docs:[['facebook/docusaurus','Easy-to-maintain docs sites built with React and MDX.','TypeScript',57000],['squidfunk/mkdocs-material','The award-winning Material theme for MkDocs.','Python',21000],['shuding/nextra','The Next.js-based docs framework of choice.','TypeScript',12000],['rust-lang/mdBook','Create books from Markdown — like GitBook, in Rust.','Rust',18000]],
pdf:[['typst/typst','A new markup-based typesetting system — LaTeX without the pain.','Rust',36000],['py-pdf/pypdf','A pure-Python PDF library: split, merge, transform.','Python',8000],['Hopding/pdf-lib','Create and modify PDF documents in any JavaScript environment.','TypeScript',7000],['diegomura/react-pdf','Use React to create PDF documents.','JavaScript',15000]],
schedule:[['temporalio/temporal','Durable execution engine for workflows and async orchestration.','Go',12000],['taskforcesh/bullmq','Robust message queue for Node.js, backed by Redis.','TypeScript',7000],['riverqueue/river','Fast and reliable background jobs in Go, Postgres-backed.','Go',5000],['agronholm/apscheduler','Job scheduling library for Python.','Python',6000]],
terminal:[['starship/starship','The minimal, blazing-fast, infinitely customizable prompt.','Rust',46000],['atuinsh/atuin','Magical shell history — searchable, synced, everywhere.','Rust',21000],['zellij-org/zellij','A terminal workspace with batteries included.','Rust',22000],['alacritty/alacritty','A cross-platform, GPU-accelerated terminal emulator.','Rust',56000]],
dotfiles:[['twpayne/chezmoi','Manage your dotfiles across machines, securely and declaratively.','Go',14000],['nix-community/home-manager','Manage your user environment with Nix.','Nix',7000],['anishathalye/dotbot','A tool that bootstraps your dotfiles.','Python',6000],['TheLocehiliosan/yadm','Yet Another Dotfiles Manager — git, without symlinks.','Python',5000]],
llm:[['ollama/ollama','Get up and running with large language models locally.','Go',97000],['open-webui/open-webui','User-friendly AI interface — ChatGPT-grade UI for local models.','Svelte',70000],['langgenius/dify','Open-source LLM app platform — agents, workflows, RAG.','TypeScript',52000],['continuedev/continue','The open-source AI code assistant for VS Code and JetBrains.','TypeScript',25000]],
types:[['colinhacks/zod','TypeScript-first schema validation with static type inference.','TypeScript',34000],['fabian-hiller/valibot','The modular and type-safe schema library.','TypeScript',3000],['arktypeio/arktype',"TypeScript's 1:1 validator, optimized from editor to runtime.",'TypeScript',3000],['effect-TS/effect','A fully typed ecosystem for building robust applications.','TypeScript',8000]],
};

export const SAMPLE = `# Project context — ledger-ui

A Next.js 14 dashboard for a small accounting firm. Everything is TypeScript; styling is Tailwind. The data layer is Prisma on top of Postgres, deployed to Vercel through GitHub Actions CI. State is mostly React Query plus a bit of Zustand. The Cursor agent spends most of its day writing React components and API routes; tests run on vitest.`;

export const STOP = new Set(['with','that','this','from','have','want','need','when','them','they','their','your','about','would','could','should','there','these','those','very','really','always','keep','keeps','making','make','using','again','every','some','more','most','into','over','hate','dread']);
